In [91]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
from selenium import webdriver
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.ticker as ticker
import pickle

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)

In [3]:
pip install nba_api

Requirement already satisfied: nba_api in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (1.1.9)
Requirement already satisfied: requests in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (from nba_api) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (from requests->nba_api) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (from requests->nba_api) (2021.5.30)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (from requests->nba_api) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/dillmedd/opt/anaconda3/envs/learn-env/lib/python3.8/site-packages (from requests->nba_api) (1.25.10)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2012-13,00,1610612740,NOH,20.0,64,60,1846.0,349,676,0.516,0,6,0.000,169,225,0.751,165,357,522,63,75,112,89,158,867
1,203076,2013-14,00,1610612740,NOP,21.0,67,66,2358.0,522,1005,0.519,2,9,0.222,348,440,0.791,207,466,673,105,89,189,109,200,1394
2,203076,2014-15,00,1610612740,NOP,22.0,68,68,2455.0,642,1199,0.535,1,12,0.083,371,461,0.805,173,523,696,149,100,200,95,141,1656
3,203076,2015-16,00,1610612740,NOP,23.0,61,61,2164.0,560,1136,0.493,35,108,0.324,326,430,0.758,130,497,627,116,78,125,121,148,1481
4,203076,2016-17,00,1610612740,NOP,24.0,75,75,2708.0,770,1526,0.505,40,134,0.299,519,647,0.802,172,712,884,157,94,167,181,168,2099
5,203076,2017-18,00,1610612740,NOP,25.0,75,75,2727.0,780,1462,0.534,55,162,0.340,495,598,0.828,187,644,831,174,115,193,162,159,2110
6,203076,2018-19,00,1610612740,NOP,26.0,56,56,1850.0,530,1026,0.517,48,145,0.331,344,433,0.794,174,498,672,218,88,135,112,132,1452
7,203076,2019-20,00,1610612747,LAL,27.0,62,62,2131.0,551,1096,0.503,72,218,0.330,444,525,0.846,142,435,577,200,91,143,154,156,1618
8,203076,2020-21,00,1610612747,LAL,28.0,36,36,1162.0,301,613,0.491,26,100,0.260,158,214,0.738,62,224,286,110,45,59,74,60,786

In [4]:
from nba_api.stats.endpoints import leaguegamefinder

gamefinder = leaguegamefinder.LeagueGameFinder()
games = gamefinder.get_data_frames()[0]
games.head(5)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22021,1610612748,MIA,Miami Heat,0022100028,2021-10-23,MIA @ IND,None,48,24,...,0.750,3,10,13,5,0,0,5,3,-4.0
1,22021,1610612739,CLE,Cleveland Cavaliers,0022100027,2021-10-23,CLE vs. ATL,None,156,69,...,0.750,8,29,37,19,2,5,9,9,-2.6
2,22021,1610612754,IND,Indiana Pacers,0022100028,2021-10-23,IND vs. MIA,None,48,28,...,0.000,4,8,12,6,2,1,2,2,4.0
3,22021,1610612737,ATL,Atlanta Hawks,0022100027,2021-10-23,ATL @ CLE,None,133,62,...,0.500,9,20,29,16,5,1,4,16,1.4
4,22021,1610612764,WAS,Washington Wizards,0022100019,2021-10-22,WAS vs. IND,W,265,135,...,0.947,6,32,38,24,5,6,9,21,1.0

Use list of NBA teams to filter Boxscore Dataframe to only NBA games

In [5]:
nba_teams = ['Golden State Warriors','Boston Celtics','Toronto Raptors','Houston Rockets','Cleveland Cavaliers','Miami Heat','San Antonio Spurs','Milwaukee Bucks','Portland Trail Blazers','Utah Jazz','Atlanta Hawks','Los Angeles Lakers','Philadelphia 76ers','Memphis Grizzlies','Denver Nuggets','Washington Wizards','Dallas Mavericks','LA Clippers','Oklahoma City Thunder','Brooklyn Nets','Indiana Pacers','Phoenix Suns','New Orleans Pelicans','Chicago Bulls','Sacramento Kings','Orlando Magic','Charlotte Hornets','Detroit Pistons','Minnesota Timberwolves','New York Knicks']

In [6]:
games_nba = games.loc[games['TEAM_NAME'].apply(lambda x: x in (nba_teams))]

Filtering dataframes by season and only including Regular Season games

In [7]:
season21 = games_nba.loc[games_nba.SEASON_ID == '22020'].reset_index(drop=True)

season20 = games_nba.loc[games_nba.SEASON_ID == '22019'].reset_index(drop=True)

season19 = games_nba.loc[games_nba.SEASON_ID == '22018'].head(2460).reset_index(drop=True)

season18 = games_nba.loc[games_nba.SEASON_ID == '22017'].head(2460).reset_index(drop=True)

season17 = games_nba.loc[games_nba.SEASON_ID == '22016'].head(2460).reset_index(drop=True)

season16 = games_nba.loc[games_nba.SEASON_ID == '22015'].head(2460).reset_index(drop=True)

In [9]:
games_nba.loc[games_nba.SEASON_ID == '22015']

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
24911,22015,1610612739,CLE,Cleveland Cavaliers,0021501220,2016-04-13,CLE vs. DET,L,265,110,...,0.733,8,35,43,21,4,7,10,23,-2.0
24912,22015,1610612753,ORL,Orlando Magic,0021501219,2016-04-13,ORL @ CHA,L,240,103,...,0.611,5,34,39,22,7,4,10,18,-14.0
24913,22015,1610612758,SAC,Sacramento Kings,0021501224,2016-04-13,SAC @ HOU,L,238,81,...,0.462,15,34,49,21,11,4,17,17,-35.0
24914,22015,1610612754,IND,Indiana Pacers,0021501225,2016-04-13,IND @ MIL,W,240,97,...,0.800,12,36,48,28,8,3,17,14,5.0
24915,22015,1610612757,POR,Portland Trail Blazers,0021501230,2016-04-13,POR vs. DEN,W,241,107,...,0.818,13,32,45,19,11,8,15,19,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29100,22015,1610612746,LAC,LA Clippers,1421500003,2015-07-04,LAC vs. ORB,L,210,74,...,0.417,8,35,43,18,10,7,18,23,-1.0
29101,22015,1610612748,MIA,Miami Heat,1421500001,2015-07-04,MIA @ IND,W,202,92,...,0.781,12,19,31,20,11,6,15,24,16.0
29102,22015,1610612763,MEM,Memphis Grizzlies,1421500005,2015-07-04,MEM @ BKN,W,200,81,...,0.818,10,25,35,14,9,1,13,23,8.0
29103,22015,1610612760,OKC,Oklahoma City Thunder,1421500004,2015-07-04,OKC vs. CHA,W,200,76,...,0.609,12,30,42,20,7,2,17,20,2.0
29104,22015,1610612751,BKN,Brooklyn Nets,1421500005,2015-07-04,BKN vs. MEM,L,201,73,...,0.529,10,26,36,15,6,4,19,27,-8.0

In [80]:
season20 = season20.loc[season20.GAME_DATE >= '2019-10-22']
season20 = season20.reset_index(drop=True)

In [122]:
#with open('data/pickles/season21.p', 'wb') as writefile: 
   # pickle.dump(season21, writefile)
    
with open('data/pickles/season20.p', 'wb') as writefile: 
    pickle.dump(season20, writefile)
    
with open('data/pickles/season19.p', 'wb') as writefile: 
    pickle.dump(season19, writefile)
    
with open('data/pickles/season18.p', 'wb') as writefile: 
    pickle.dump(season18, writefile)
    
with open('data/pickles/season17.p', 'wb') as writefile: 
    pickle.dump(season17, writefile)
    
with open('data/pickles/season16.p', 'wb') as writefile: 
    pickle.dump(season16, writefile)

In [14]:
def combine_team_games(df, keep_method='home'):
    '''Combine a TEAM_ID-GAME_ID unique table into rows by game. Slow.

        Parameters
        ----------
        df : Input DataFrame.
        keep_method : {'home', 'away', 'winner', 'loser', ``None``}, default 'home'
            - 'home' : Keep rows where TEAM_A is the home team.
            - 'away' : Keep rows where TEAM_A is the away team.
            - 'winner' : Keep rows where TEAM_A is the losing team.
            - 'loser' : Keep rows where TEAM_A is the winning team.
            - ``None`` : Keep all rows. Will result in an output DataFrame the same
                length as the input DataFrame.
                
        Returns
        -------
        result : DataFrame
    '''
    # Join every row to all others with the same game ID.
    joined = pd.merge(df, df, suffixes=['_A', '_B'],
                      on=['SEASON_ID', 'GAME_ID', 'GAME_DATE'])
    # Filter out any row that is joined to itself.
    result = joined[joined.TEAM_ID_A != joined.TEAM_ID_B]
    # Take action based on the keep_method flag.
    if keep_method is None:
        # Return all the rows.
        pass
    elif keep_method.lower() == 'home':
        # Keep rows where TEAM_A is the home team.
        result = result[result.MATCHUP_A.str.contains(' vs. ')]
    elif keep_method.lower() == 'away':
        # Keep rows where TEAM_A is the away team.
        result = result[result.MATCHUP_A.str.contains(' @ ')]
    elif keep_method.lower() == 'winner':
        result = result[result.WL_A == 'W']
    elif keep_method.lower() == 'loser':
        result = result[result.WL_A == 'L']
    else:
        raise ValueError(f'Invalid keep_method: {keep_method}')
    return result

Combine games on dataframes for purpose of creating df with advanced stats and four factors stats for each game

In [81]:
loop_season21 = combine_team_games(season21)
loop_season20 = combine_team_games(season20)
loop_season19 = combine_team_games(season19)
loop_season18 = combine_team_games(season18)
loop_season17 = combine_team_games(season17)
loop_season16 = combine_team_games(season16)

In [82]:
loop_season21.reset_index(inplace=True, drop=True)
loop_season20.reset_index(inplace=True, drop=True)
loop_season19.reset_index(inplace=True, drop=True)
loop_season18.reset_index(inplace=True, drop=True)
loop_season17.reset_index(inplace=True, drop=True)
loop_season16.reset_index(inplace=True, drop=True)

Create new dataframes for advanced boxscore stats, four_factors stats using a for loop to append each game's stats together

In [95]:
from nba_api.stats.endpoints import boxscoreadvancedv2
#Advanced Stats by gameID
boxscore21 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season21['GAME_ID'][0])
bs_df21 = boxscore21.get_data_frames()[1]

In [98]:
for n in range(1, len(loop_season21)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season21['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df21 = bs_df21.append(dfn2)
    
    
with open('data/pickles/boxscoreadv21.p', 'wb') as writefile: 
    pickle.dump(bs_df21, writefile)

In [99]:
from nba_api.stats.endpoints import boxscorefourfactorsv2
#FourFactors
ffboxscore21 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season21['GAME_ID'][0]))
ff_df21 = ffboxscore.get_data_frames()[1]

In [100]:
for n in range(1, len(loop_season21)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season21['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df21 = ff_df21.append(dfn2)
    
with open('data/pickles/fourfactors21.p', 'wb') as writefile: 
    pickle.dump(ff_df21, writefile)

In [105]:
with open('data/pickles/fourfactors21.p', 'wb') as writefile: 
    pickle.dump(ff_df21, writefile)

Do the same with seasons 16-20

In [85]:
boxscore20 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season20['GAME_ID'][0])
boxscore19 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season19['GAME_ID'][0])
boxscore18 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season18['GAME_ID'][0])
boxscore17 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season17['GAME_ID'][0])
boxscore16 = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = loop_season16['GAME_ID'][0])
bs_df20 = boxscore20.get_data_frames()[1]
bs_df19 = boxscore19.get_data_frames()[1]
bs_df18 = boxscore18.get_data_frames()[1]
bs_df17 = boxscore17.get_data_frames()[1]
bs_df16 = boxscore16.get_data_frames()[1]

In [86]:
ffboxscore20 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season20['GAME_ID'][0]))
ff_df20 = ffboxscore20.get_data_frames()[1]

ffboxscore19 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season19['GAME_ID'][0]))
ff_df19 = ffboxscore19.get_data_frames()[1]

ffboxscore18 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season18['GAME_ID'][0]))
ff_df18 = ffboxscore.get_data_frames()[1]

ffboxscore17 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season17['GAME_ID'][0]))
ff_df17 = ffboxscore.get_data_frames()[1]

ffboxscore16 = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season16['GAME_ID'][0]))
ff_df16 = ffboxscore.get_data_frames()[1]

In [128]:
ff_df18

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0022000002,1610612747,Lakers,LAL,Los Angeles,240:00,0.525,0.383,0.18,0.182,0.548,0.204,0.15,0.269
1,0022000002,1610612746,Clippers,LAC,LA,240:00,0.548,0.204,0.15,0.212,0.525,0.383,0.18,0.250

In [116]:
for n in range(1, len(loop_season20)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season20['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df20 = bs_df20.append(dfn2)
    
for n in range(1, len(loop_season20)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season20['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df20 = ff_df20.append(dfn2)

In [117]:
with open('data/pickles/boxscoreadv20.p', 'wb') as writefile: 
    pickle.dump(bs_df20, writefile)

with open('data/pickles/fourfactors20.p', 'wb') as writefile: 
    pickle.dump(ff_df20, writefile)

In [123]:
for n in range(1, len(loop_season19)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season19['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df19 = bs_df19.append(dfn2)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [134]:
bs_df19

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0021801229,1610612762,Jazz,UTA,Utah,265:00,113.7,115.1,120.0,119.2,-6.3,-4.0,0.660,1.82,18.4,0.339,0.750,0.534,14.106,14.3,0.509,0.568,1.0,0.199,108.55,108.23,90.19,119,0.484
1,0021801229,1610612746,Clippers,LAC,LA,265:00,120.0,119.2,113.7,115.1,6.3,4.0,0.630,2.83,20.6,0.250,0.661,0.466,10.067,10.0,0.566,0.600,1.0,0.200,108.55,108.23,90.19,120,0.516
0,0021801221,1610612748,Heat,MIA,Miami,240:00,84.2,87.0,103.6,104.6,-19.4,-17.6,0.579,1.47,15.5,0.188,0.694,0.456,13.441,13.9,0.429,0.449,1.0,0.196,110.34,108.00,90.00,108,0.433
1,0021801221,1610612751,Nets,BKN,Brooklyn,240:00,103.6,104.6,84.2,87.0,19.4,17.6,0.674,2.42,18.3,0.306,0.813,0.544,11.001,11.1,0.469,0.483,1.0,0.198,110.34,108.00,90.00,108,0.567
0,0021801222,1610612753,Magic,ORL,Orlando,240:00,130.1,131.2,121.4,122.6,8.6,8.6,0.500,4.00,18.9,0.286,0.816,0.538,6.397,6.5,0.608,0.630,1.0,0.200,93.84,93.00,77.50,93,0.519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,0021800011,1610612758,Kings,SAC,Sacramento,240:00,109.4,109.3,114.2,115.0,-4.8,-5.6,0.347,1.89,13.2,0.143,0.795,0.452,8.418,8.4,0.553,0.568,1.0,0.200,107.32,107.00,89.17,107,0.447
0,0021800001,1610612755,76ers,PHI,Philadelphia,240:00,81.2,82.1,98.9,100.0,-17.7,-17.9,0.529,1.13,13.7,0.175,0.750,0.460,14.937,15.1,0.420,0.448,1.0,0.200,106.64,105.50,87.92,106,0.405
1,0021800001,1610612738,Celtics,BOS,Boston,240:00,98.9,100.0,81.2,82.1,17.7,17.9,0.500,1.40,15.1,0.250,0.825,0.540,14.130,14.3,0.490,0.509,1.0,0.198,106.64,105.50,87.92,105,0.595
0,0021800002,1610612760,Thunder,OKC,Oklahoma City,240:00,94.1,97.1,101.0,104.9,-6.9,-7.8,0.636,1.40,14.7,0.348,0.585,0.454,14.114,14.6,0.418,0.466,1.0,0.200,106.60,103.00,85.83,103,0.418
1,0021800002,1610612744,Warriors,GSW,Golden State,240:00,101.0,104.9,94.1,97.1,6.9,7.8,0.667,1.33,18.4,0.415,0.652,0.546,19.641,20.4,0.479,0.525,1.0,0.199,106.60,103.00,85.83,103,0.582

In [129]:
for n in range(1, len(loop_season19)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season19['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df19 = ff_df19.append(dfn2)

In [132]:
ff_df19

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0021801229,1610612762,Jazz,UTA,Utah,265:00,0.509,0.311,0.141,0.274,0.566,0.283,0.101,0.250
1,0021801229,1610612746,Clippers,LAC,LA,265:00,0.566,0.283,0.101,0.214,0.509,0.311,0.141,0.339
0,0021801221,1610612748,Heat,MIA,Miami,240:00,0.429,0.153,0.134,0.125,0.469,0.061,0.110,0.306
1,0021801221,1610612751,Nets,BKN,Brooklyn,240:00,0.469,0.061,0.110,0.278,0.429,0.153,0.134,0.188
0,0021801222,1610612753,Magic,ORL,Orlando,240:00,0.608,0.227,0.064,0.214,0.577,0.346,0.085,0.184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,0021800011,1610612758,Kings,SAC,Sacramento,240:00,0.553,0.189,0.084,0.102,0.601,0.481,0.158,0.205
0,0021800001,1610612755,76ers,PHI,Philadelphia,240:00,0.420,0.264,0.149,0.105,0.490,0.144,0.141,0.250
1,0021800001,1610612738,Celtics,BOS,Boston,240:00,0.490,0.144,0.141,0.214,0.420,0.264,0.149,0.175
0,0021800002,1610612760,Thunder,OKC,Oklahoma City,240:00,0.418,0.407,0.141,0.242,0.479,0.189,0.196,0.415
1,0021800002,1610612744,Warriors,GSW,Golden State,240:00,0.479,0.189,0.196,0.321,0.418,0.407,0.141,0.348

In [133]:
with open('data/pickles/boxscoreadv19.p', 'wb') as writefile: 
    pickle.dump(bs_df19, writefile)

with open('data/pickles/fourfactors19.p', 'wb') as writefile: 
    pickle.dump(ff_df19, writefile)

FileNotFoundError: [Errno 2] No such file or directory: 'data/pickles/boxscoreadv19.p'

In [130]:
for n in range(1, len(loop_season18)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season18['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df18 = bs_df18.append(dfn2)
    
for n in range(1, len(loop_season18)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season18['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df18 = ff_df18.append(dfn2)

In [ ]:
with open('data/pickles/boxscoreadv18.p', 'wb') as writefile: 
    pickle.dump(bs_df18, writefile)

with open('data/pickles/fourfactors18.p', 'wb') as writefile: 
    pickle.dump(ff_df18, writefile)

In [131]:
for n in range(1, len(loop_season17)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season17['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df17 = bs_df17.append(dfn2)
    
for n in range(1, len(loop_season17)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season17['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df17 = ff_df17.append(dfn2)

In [ ]:
with open('data/pickles/boxscoreadv17.p', 'wb') as writefile: 
    pickle.dump(bs_df17, writefile)

with open('data/pickles/fourfactors17.p', 'wb') as writefile: 
    pickle.dump(ff_df17, writefile)

In [ ]:
for n in range(1, len(loop_season16)):
    dfn = boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = (loop_season16['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    bs_df16 = bs_df16.append(dfn2)

for n in range(1, len(loop_season16)):
    dfn = boxscorefourfactorsv2.BoxScoreFourFactorsV2(game_id = (loop_season16['GAME_ID'][n]))
    dfn2 = dfn.get_data_frames()[1]
    ff_df16 = ff_df16.append(dfn2)

In [ ]:
with open('data/pickles/boxscoreadv16.p', 'wb') as writefile: 
    pickle.dump(bs_df16, writefile)

with open('data/pickles/fourfactors16.p', 'wb') as writefile: 
    pickle.dump(ff_df16, writefile)

In [77]:
df21 = pd.merge(season21, bs_df21, on = ['GAME_ID', 'TEAM_ID'], copy=False).drop(labels=['TEAM_NAME_y', 'TEAM_ABBREVIATION_y', 'MIN_y'], axis=1)
df21.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE,MATCHUP,WL,MIN_x,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,TEAM_CITY,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,22020,1610612765,DET,Detroit Pistons,0022001069,2021-05-16,DET vs. MIA,L,240,107,40,86,0.465,11,35,0.314,16,22,0.727,7,26,33,26,4,4,16,21,-13.0,Detroit,102.2,110.3,121.5,122.4,-19.2,-12.1,0.650,1.63,18.9,0.245,0.769,0.477,15.285,16.5,0.529,0.559,1.0,0.193,101.74,97.5,81.25,97,0.386
1,22020,1610612737,ATL,Atlanta Hawks,0022001066,2021-05-16,ATL vs. HOU,W,240,124,49,90,0.544,7,21,0.333,19,26,0.731,11,45,56,32,10,8,13,16,29.0,Atlanta,119.9,120.4,89.8,93.1,30.1,27.3,0.653,2.46,21.9,0.298,0.750,0.559,12.568,12.6,0.583,0.611,1.0,0.199,104.62,102.5,85.42,103,0.678
2,22020,1610612761,TOR,Toronto Raptors,0022001079,2021-05-16,TOR vs. IND,L,240,113,39,97,0.402,12,38,0.316,23,29,0.793,16,32,48,21,8,3,12,12,-12.0,Toronto,106.8,107.6,118.0,117.9,-11.2,-10.3,0.538,1.75,14.7,0.322,0.729,0.505,11.346,11.4,0.464,0.515,1.0,0.202,105.84,105.5,87.92,105,0.428
3,22020,1610612755,PHI,Philadelphia 76ers,0022001075,2021-05-16,PHI vs. ORL,W,241,128,46,94,0.489,19,40,0.475,17,23,0.739,9,32,41,35,8,5,11,27,11.0,Philadelphia,119.5,123.1,114.7,112.5,4.8,10.6,0.761,2.92,23.2,0.196,0.744,0.447,11.202,11.5,0.590,0.615,1.0,0.195,104.58,104.0,86.67,104,0.539
4,22020,1610612747,LAL,Los Angeles Lakers,0022001072,2021-05-16,LAL @ NOP,W,238,110,45,96,0.469,11,35,0.314,9,15,0.600,8,34,42,30,14,5,9,16,12.0,Los Angeles,105.2,110.0,97.8,99.0,7.4,11.0,0.667,3.00,21.0,0.278,0.791,0.505,9.560,10.0,0.526,0.536,1.0,0.199,102.42,99.5,82.92,100,0.560

In [111]:
from nba_api.stats.endpoints import boxscorescoringv2
#scoring stats
ssboxscore = boxscorescoringv2.BoxScoreScoringV2(game_id = '0021601229')
ssboxscore.get_data_frames()[1]

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,PCT_FGA_2PT,PCT_FGA_3PT,PCT_PTS_2PT,PCT_PTS_2PT_MR,PCT_PTS_3PT,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0021601229,1610612747,Lakers,LAL,Los Angeles,240:00,0.817,0.183,0.787,0.128,0.128,0.340,0.085,0.287,0.660,0.568,0.432,0.500,0.500,0.561,0.439
1,0021601229,1610612744,Warriors,GSW,Golden State,240:00,0.600,0.400,0.532,0.147,0.330,0.211,0.138,0.174,0.385,0.552,0.448,0.833,0.167,0.634,0.366